{{- if .Values.database.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.database.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.database.storage.className }}
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
{{- end }} 