apiVersion: v1
kind: Secret
metadata:
  name: auth0-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  secret: {{ .Values.secrets.auth0.secret | b64enc }}
  issuerBaseUrl: {{ .Values.secrets.auth0.issuerBaseUrl | b64enc }}
  clientId: {{ .Values.secrets.auth0.clientId | b64enc }}
  clientSecret: {{ .Values.secrets.auth0.clientSecret | b64enc }}
  audience: {{ .Values.secrets.auth0.audience | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  password: {{ .Values.secrets.database.password | b64enc }}
  url: {{ .Values.secrets.database.url | b64enc }} 