apiVersion: v2
name: container-app
description: A Helm chart for per-user containerized application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - containers
  - auth0
  - nextjs
  - traefik
home: https://github.com/your-org/container-app
sources:
  - https://github.com/your-org/container-app
maintainers:
  - name: Your Name
    email: your.email@example.com 